
resource_types:

  - name: github-pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:

  - name: code
    type: git
    icon: github
    source:
      uri: https://github.com/a1ezzz/pyknic
      branch: ((branch))

  - name: pull-request
    type: github-pull-request
    source:
        repository: a1ezzz/pyknic
        access_token: ((github-access-token))

jobs:
  - name: pyknic-test-job-py-((python_version))
    build_log_retention:
      builds: 20
    plan:

      - get: pull-request
    
      - get: code
        trigger: true

      - put: pull-request
        params:
          path: pull-request
          status: pending
          context: py-((python_version))-pytest

      - put: pull-request
        params:
          path: pull-request
          status: pending
          context: py-((python_version))-mypy

      - task: prepare_venv
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python  # TODO: replace!!!
              tag: ((python_version))
          outputs:
            - name: sandbox
              path: /sandbox
          caches:
            - path: sandbox/pip-cache
          run:
            path: /bin/bash
            args:
              - -ecx
              - |
                mkdir -p /sandbox/pip-cache
                pip3 --cache-dir /sandbox/pip-cache install virtualenv  # TODO: it is better to do this inside base container
                virtualenv -p /usr/local/bin/python /sandbox/venv

      - task: install_dependencies
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: ((python_version))
          inputs:
            - name: sandbox
              path: /sandbox
            - name: code
          outputs:
            - name: sandbox
              path: /sandbox
          caches:
            - path: /sandbox/pip-cache
          run:
            dir: code
            path: /bin/bash
            args:
              - -ecx
              - |
                source /sandbox/venv/bin/activate
                /sandbox/venv/bin/pip3 --cache-dir /sandbox/pip-cache install '.[all]'

      - task: run_tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: ((python_version))
          inputs:
            - name: sandbox
              path: /sandbox
            - name: code
          run:
            dir: code
            path: /bin/bash
            args:
              - -ecx
              - |
                source /sandbox/venv/bin/activate
                pytest -v

        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
            context: py-((python_version))-pytest

      - task: run_mypy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: ((python_version))
          inputs:
            - name: sandbox
              path: /sandbox
            - name: code
          run:
            dir: code
            path: /bin/bash
            args:
              - -ecx
              - |
                source /sandbox/venv/bin/activate
                mypy --install-types --non-interactive
                mypy

        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure
            context: py-((python_version))-mypy

      - put: pull-request
        params:
          path: pull-request
          status: success                
          context: py-((python_version))-pytest

      - put: pull-request
        params:
          path: pull-request
          status: success                
          context: py-((python_version))-mypy
