

resource_types:

  - name: github-pr-resource
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:

  - name: pull-request
    type: github-pr-resource
    source:
        repository: a1ezzz/pyknic
        access_token: ((github-access-token))

jobs:
  - name: pyknic-pr-tests
    build_log_retention:
      builds: 20
    plan:

      - get: pull-request
        version: every
        trigger: true

      - put: pull-request
        params:
          path: pull-request
          status: pending
          context: pytest

      - put: pull-request
        params:
          path: pull-request
          status: pending
          context: mypy

      - task: test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python  # TODO: replace!!!
              tag: 3.12
          run:
            path: /bin/bash
            args:
              - -ecx
              - |
                echo "Hello!"
