
resource_types:
  - name: git-branches
    type: registry-image
    source:
      repository: aoldershaw/git-branches-resource

resources:

  - name: ci-branches
    type: git-branches
    icon: github
    source:
      uri: https://github.com/a1ezzz/pyknic

  - name: ci-code
    type: git
    icon: github
    source:
      uri: https://github.com/a1ezzz/pyknic
      branch: "main"

jobs:
  - name: set-pipelines
    build_log_retention:
      builds: 15
    plan:
      - in_parallel:

        - get: ci-branches
          trigger: true

        - get: ci-code

      - load_var: branches
        file: ci-branches/branches.json

      - try:
          across:
          - var: branch
            values: ((.:branches))

          set_pipeline: pyknic-test-3.12
          file: ci-code/concourse-ci/pyknic-test.yml
          instance_vars:
            branch: ((.:branch.name))
          vars:
            branch: ((.:branch.name))
            commit: ""
            github-access-token: ""
            pull_request_branch_name: ""
            python_version: 3.12

      - try:
          across:
          - var: branch
            values: ((.:branches))

          set_pipeline: pyknic-test-3.11
          file: ci-code/concourse-ci/pyknic-test.yml
          instance_vars:
            branch: ((.:branch.name))
          vars:
            branch: ((.:branch.name))
            commit: ""
            github-access-token: ""
            pull_request_branch_name: ""
            python_version: 3.11
