
pyknic:
    fastapi:
        apps: []
        swagger: no
        redoc:   no
        openapi: no

        uvicorn_host: 127.0.0.1
        uvicorn_port: 8000

        tgbot_word_games:
            url_path: /tgbot/word_games

        lobby:

            jwt:
                algorithm: 'RS256'
                audience: 'pyknic::lobby::user'
                leeway: 10
                ttl: 1800

            private_key_location:
            private_key_default_size: 4096

            response_signing_hash: sha512

            main_url_path: /api/v1/lobby

            aaa_policies: {}
